import type { Metadata } from 'next';
import { Electrolize, Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from './components/Header';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const electrolize = Electrolize({
  variable: '--font-electrolize',
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'sparkForge',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${electrolize.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
